### ISSUE TITLE
Metrics bridge JSON "source" field name change

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hawkular-metrics#12]
The metrics bridge expects data in this format:
```json
{"source": "my-user-metric", "value": 3.234}
```
The `source` field name was chosen to map `SingleMetric` class field.

But what Hawkular Metrics uses all over its API is `id`.

**Comment by tsegismont** [comment]
@cescoffier ok to change?

**Comment by cescoffier** [comment]
No problem for me. Was copying the SimpleMetrics class, but `id` is fine too.

**Comment by cescoffier** [comment]
Fixed in the initial-work branch.

**Comment by tsegismont** [comment]
Perfect! And thanks for the commit, I just wanted to know if that was an immediate problem for your demo setup.
