### ISSUE TITLE
Enable sending designed kinds of mertics

### ISSUE THREAD

**Issue by auszone** [vert-x3/vertx-hawkular-metrics#19]
It’s not possible yet to disable individual metrics in current impl.
In order to achieve sending designed kinds of metrics, it should be able to disable individual metrics.

**Comment by auszone** [comment]
One possible way to resolve this is keep a collection in `VertxHawkularOptions` which holds disabled metrics. And then scheduler only registers metrics that is NOT in the collection.

**Comment by tsegismont** [comment]
Fixed by PR #20
