### ISSUE TITLE
Add integration test for metrics bridge

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hawkular-metrics#2]
The feature has been tested manually but an integration test would be nice.

**Comment by cescoffier** [comment]
Will do it.

**Comment by cescoffier** [comment]
Has been fixed in the initial-work branch.

**Comment by tsegismont** [comment]
Thanks Clément! Can we close the issue?

**Comment by cescoffier** [comment]
One sec ;-)

Fixing something. Then it can be closed.

**Comment by cescoffier** [comment]
Ok done. It can be closed now.
