### ISSUE TITLE
NPE when starting JS verticle with metrics bridge enabled

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hawkular-metrics#4]
The verticle is started like this:

```bash
vertx run app.js -Dvertx.metrics.options.enabled=true -Dvertx.metrics.options.metricsBridgeEnabled=true -Dvertx.metrics.options.metricsBridgeAddress=metrics
```

This stacktrace appears in the console:

```
Unhandled exception 
java.lang.NullPointerException
        at io.vertx.ext.hawkular.impl.Sender.lambda$new$17(Sender.java:82)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$34(ContextImpl.java:335)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

The problem did not show up until I started to activate the metrics bridge. Also, it is intermittent.

**Comment by tsegismont** [comment]
@cescoffier does that ring a bell?

**Comment by cescoffier** [comment]
Gonna have a look.

**Comment by cescoffier** [comment]
The eventBus is `null`. Investigating....

**Comment by pmlopes** [comment]
probably the order of the require statements needs to be reshuffled, require needs to have the right order otherwise you get incomplete objects

**Comment by pmlopes** [comment]
probably a similar issue like this: https://github.com/vert-x3/vertx-auth/issues/29

**Comment by cescoffier** [comment]
I'm not sure. I've reproduced it using a fat jar with a very simple verticle:

```
vertx.createHttpServer().requestHandler(function (req) {
    req.response().putHeader("content-type", "text/html").end("<html><body><h1>Hello from vert.x!</h1></body></html>");
}).listen(8080);
```

So no `requires`.

**Comment by cescoffier** [comment]
It might be the bug actually.... It only happens in js.

**Comment by purplefox** [comment]
Do you have a link to the Sender.java file? I can't see any source in this repository.

**Comment by cescoffier** [comment]
@purplefox here it is: https://github.com/tsegismont/vertx-hawkular-metrics/blob/initial-work/src/main/java/io/vertx/ext/hawkular/impl/Sender.java

**Comment by purplefox** [comment]
Ah ok, this should really be in the initial-work branch of this repo though.

**Comment by cescoffier** [comment]
Issue reproducible in groovy too.

**Comment by purplefox** [comment]
Most probably your trying to get the eventBus from vertx before it's been initialised properly.

Looking at VertxImpl constructor initialiseMetrics(options); is called before the event bus is created.

And.. in the clustered case the event bus won't be set until the cluster has been joined.

**Comment by cescoffier** [comment]
Yes, looking at the same code right now. 

Should `this.metrics` we set after the initialization of the event bus ? Or metric providers cannot use the event bus (as there are no way to know when it will be initialized).

**Comment by purplefox** [comment]
Probably VertxImpl.metrics shouldn't be set before the event bus is initialised and any attempt to get metrics before that should throw an exception.

**Comment by cescoffier** [comment]
Ok, will work on a PR.

**Comment by cescoffier** [comment]
Not sure we can really delay the metrics initialization in the clustered with HA case, as the HA is populating some metrics (timer). 

Another way would be to notify the metric provider when the event bus is initialized.

**Comment by tsegismont** [comment]
@cescoffier if this is too big to be addressed before 3.2, a workaround could be to delay the metrics bridge setup until the event is initialized?

**Comment by cescoffier** [comment]
@tsegismont no it will be fixed before 3.2.

**Comment by tsegismont** [comment]
@cescoffier I mean, something like:

```java
      // Configure the metrics bridge. It just transforms the received metrics (json) to a Single Metric to enqueue it.
      if (options.isMetricsBridgeEnabled() && options.getMetricsBridgeAddress() != null) {
        vertx.setTimer(1000, t -> configureMetricsBridge(context, options.getMetricsBridgeAddress()));
      }
```

And a new method:

```java
  private void configureMetricsBridge(Context context, String bridgeAddress) {
    EventBus eventBus = vertx.eventBus();
    if (eventBus == null) {
      // Event bus not ready yet
      vertx.setTimer(1000, t -> configureMetricsBridge(context, bridgeAddress));
      return;
    }
    eventBus.consumer(bridgeAddress, message -> {
      // By spec, it is a json object.
      JsonObject json = (JsonObject) message.body();

      // source and value has to be set.
      // the timestamp can have been set in the message using the 'timestamp' field. If not use 'now'
      // the type of metrics can have been set in the message using the 'type' field. It not use 'gauge'. Only
      // "counter" and "gauge" are supported.
      SingleMetric metric = new SingleMetric(json.getString("source"),
        json.getLong("timestamp", System.currentTimeMillis()),
        json.getDouble("value"),
        "counter".equals(json.getString("type", "")) ? MetricType.COUNTER : MetricType.GAUGE);

      context.runOnContext(v -> handle(Collections.singletonList(metric)));
    });
  }
```

Not perfect but could be enough for 3.2

**Comment by tsegismont** [comment]
@cescoffier ok, good then :)

**Comment by cescoffier** [comment]
I've opened a PR on vertx core that let us know when the event bus is initialized:
https://github.com/eclipse/vert.x/pull/1200

**Comment by cescoffier** [comment]
Has been fixed in the initial-work branch.

**Comment by tsegismont** [comment]
Thanks Clément! Can we close the issue?

**Comment by cescoffier** [comment]
Yes. I can be closed. The fix is in the latest vertx-core, and the new callback is now used by the provider.

**Comment by tsegismont** [comment]
Perfect.

**Comment by vietj** [comment]
wow, I missed this thread :-)
