### ISSUE TITLE
Metrics tagging support

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hawkular-metrics#42]
Without tagging, information on the metric is all embedded in the id string (host, component, etc). Tags is a more powerful way to put metrics in context. Also, search for metrics by name is not efficient, whereas it is by tags.

**Comment by tsegismont** [comment]
- Let the user define a list of tags which should be applied to all metrics (e.g hostname)
- Create tags for metric types/instances (e.g `vertx.metric.type=vertx.eventBus.handler.msgCount`, `vertx.metric.instance.handler=myaddress`)

**Comment by tsegismont** [comment]
@jotak can you have a look and confirm this was your understanding? Thanks

**Comment by jotak** [comment]
Looks good!

**Comment by kerko** [comment]
@tsegismont Any plans when this will be included ?

**Comment by tsegismont** [comment]
Hopefully 3.4 (next release)

2016-11-30 11:01 GMT+01:00 Jan Kerkenhoff <notifications@github.com>:
