### ISSUE TITLE
HttpClient is not ready yet when requesting since it's async.

### ISSUE THREAD

**Issue by auszone** [vert-x3/vertx-hawkular-metrics#44]
@tsegismont 
https://github.com/vert-x3/vertx-hawkular-metrics/blob/master/src/main/java/io/vertx/ext/hawkular/impl/Sender.java#L115-L122
Is is possible that when issuing http requests but the client is not ready yet since it's async.
I encountered this issue when reporting inventory.

**Comment by tsegismont** [comment]
That might be a bug, yes. Could you please paste the stacktrace? Have you thought about a fix?

**Comment by auszone** [comment]
Since it only happens once, so we can make it blocking?

**Comment by tsegismont** [comment]
We can't make this "sync". It must be created on the impl execution context. And when the constructor, is invoked, we're not on this context yet (we're called by the thread which is creating the Vert.x instance).

Please paste the stack trace.

**Comment by auszone** [comment]
It seems to be no problem now if I make them run in the same context. 👍

**Comment by tsegismont** [comment]
Ok, then let's close the issue.
