### ISSUE TITLE
Support of 'availability' metrics

### ISSUE THREAD

**Issue by llfbandit** [vert-x3/vertx-hawkular-metrics#58]
I'm trying to report availability metrics for external components to my app.
Querying the hawkular endpoint /availability return no content.

Just building this simple pseudo report:
```
JsonObject metric = new JsonObject();
metric.put("id", "external.status.ok");
metric.put("type", "availability");
metric.put("value", 1);
```

Counters & gauges are well reported. /metrics/data should support this type of metric but nothing happens...
Tested with Hawkular 0.25.

**Comment by tsegismont** [comment]
@llfbandit it's in master now, will be included in 3.4.2
