### ISSUE TITLE
Support `remoteName` in io.vertx.ext.hawkular.impl.NetClientMetricsImpl#connected

### ISSUE THREAD

**Issue by cescoffier** [vert-x3/vertx-hawkular-metrics#7]
The parameter is ignored at the moment.

**Comment by cescoffier** [comment]
Same issue for io.vertx.ext.hawkular.impl.HttpClientMetricsImpl#connected(io.vertx.core.net.SocketAddress, java.lang.String)

**Comment by tsegismont** [comment]
Yes, actually the new parameter must be used everywhere we build the metric name upon a remote address.

**Comment by tsegismont** [comment]
Fixed in initial-work branch
