### ISSUE TITLE
Configure Continuous Integration

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hawkular-metrics#8]
This module is not part of https://vertx.ci.cloudbees.com/view/vert.x-3/

Note sure I can do this myself @vietj @cescoffier

**Comment by cescoffier** [comment]
I'm on it.

**Comment by cescoffier** [comment]
Done: https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-hawkular-metrics/

Well, it's red ;-)

**Comment by cescoffier** [comment]
Notice that it builds `initial-work`, we would need to change after the merge into master.

**Comment by tsegismont** [comment]
@cescoffier Thanks for the setup. How often is the project built?

**Comment by cescoffier** [comment]
"Build when a change is pushed to GitHub"

**Comment by tsegismont** [comment]
Does it take some time before the build appears? I have pushed a few
commits to the initial-work branch but the corresponding builds don't show
up:
https://github.com/vert-x3/vertx-hawkular-metrics/commits/initial-work
https://vertx.ci.cloudbees.com/job/vert.x3-hawkular-metrics/

2015-11-24 11:07 GMT+01:00 Clement Escoffier <notifications@github.com>:

**Comment by cescoffier** [comment]
it looks like the configuration is broken for almost all projects. It did not rebuild the projects I've modified this morning.
