### ISSUE TITLE
Investigate CI issues

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-hawkular-metrics#9]
Tests do not pass in the CI env:
https://vertx.ci.cloudbees.com/view/vert.x-3/job/vert.x3-hawkular-metrics/

**Comment by tsegismont** [comment]
@cescoffier would it be possible to grant me permission to start a build manually on Cloudbees?

**Comment by cescoffier** [comment]
Do you have a cloudbee account ?

**Comment by tsegismont** [comment]
Yes (userid is my GMail account)

2015-11-25 8:04 GMT+01:00 Clement Escoffier <notifications@github.com>:

**Comment by cescoffier** [comment]
I just added you.

**Comment by tsegismont** [comment]
Just tried, I was able to start a build. Thanks!

2015-11-25 10:12 GMT+01:00 Clement Escoffier <notifications@github.com>:

**Comment by tsegismont** [comment]
Fixed by 32099f5d7c5b0cba42b492353ac44b9471c01065 and 278d6d2d342cc8e9fe3de2f6937044b9791e1f51

Two problems found:
- to verify counter and gauge values on the Hawkular server, tests used to wait at most twice the collection schedule time; this works fine on dev laptops where tests run very fast, but not on Cloudbees
- I had not paid attention to the time order of data points retrieved from the Hawkular server; so when a counter already had multiple values, the oldest value was used for comparison, instead of the newest
